### PR TITLE
Change workflow to download full result from

### PR DESCRIPTION
**Pull request by tertsdiepraam**
`CICD.yml` --> `GnuTests.yml`

Let's hope it works now

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
@sylvestre I can also commit to main without PR if you don't mind. Is that okay?

**Comment by sylvestre** [comment]
please do, I trust your judgement

**Comment by tertsdiepraam** [comment]
Oops, turns out I don't have write access yet. Could you fix that? @sylvestre

**Comment by sylvestre** [comment]
it worked anyway :)
https://github.com/uutils/coreutils-tracking/blob/main/gnu-full-result.json

**Pull request merged**
