### PR TITLE
Add empty individual-size-result.json

### PR DESCRIPTION
**Pull request by miles170**
Fix for #9. We need an initial json file to let CI generate the result.

### CODE REVIEW

**Comment by miles170** [comment]
The CI is failing since the [coreutils CI](https://github.com/uutils/coreutils/actions/runs/4718023743/jobs/8368298205) is not finished.

**Comment by sylvestre** [comment]
yeah, i know, no worries :) I am just impatient

**Comment by sylvestre** [comment]
well done 👍🏼
https://github.com/uutils/coreutils-tracking/tree/main/individual-size-results

**Comment by miles170** [comment]
> well done 👍🏼 https://github.com/uutils/coreutils-tracking/tree/main/individual-size-results

Would it be a good idea to remove the `individual-size-results` folder before generating the graphs? In case somehow binary is deleted or renamed, no superfluous graph is left.

**Comment by sylvestre** [comment]
as you wish I think it will happen rarely enough not to worry about it :)

**Pull request merged**
